openapi: 3.0.3
info:
  title: Netsuite API Contracts
  description: APIs to upload and update vendor mapping files for ingestion and processing.
  version: 1.0.0
paths:
  /api/v1/vendors/:
    post:
      summary: Register vendors for authors
      description: Create vendor records for a list of authors and return a mapping of author IDs to vendor IDs.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - authorIds
              properties:
                authorIds:
                  type: array
                  description: List of unique author IDs to register as vendors.
                  items:
                    type: string
                    example: "author-12345"
      responses:
        '201':
          description: Vendors created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorToVendorMap:
                    type: object
                    additionalProperties:
                      type: string
                    description: A mapping of author IDs to their corresponding vendor IDs.
              examples:
                success:
                  summary: Successful creation
                  value:
                    authorToVendorMap:
                      author-12345: "vendor-12345"
                      author-67890: "vendor-67890"
        '400':
          description: Bad request due to missing or invalid parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    description: Error code for the issue.
                  error:
                    type: string
                    description: Error message indicating the issue.
              examples:
                missing-authorIds:
                  summary: Missing authorIds
                  value:
                    errorCode: "MISSING_PARAMETER"
                    error: "The 'authorIds' field is required and must be a non-empty array."
                invalid-authorId:
                  summary: Invalid authorId
                  value:
                    errorCode: "INVALID_AUTHOR_ID"
                    error: "One or more 'authorIds' are invalid."
        '409':
          description: Conflict if some authors are already registered as vendors.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    description: Error code for the issue.
                  error:
                    type: string
                    description: Error message indicating the issue.
                  conflictedAuthors:
                    type: array
                    items:
                      type: string
                    description: List of author IDs that are already registered as vendors.
              examples:
                conflict:
                  summary: Some authors already registered
                  value:
                    errorCode: "AUTHORS_ALREADY_REGISTERED"
                    error: "The following authors are already registered as vendors."
                    conflictedAuthors:
                      - "author-12345"
                      - "author-67890"
        '500':
          description: Server error due to unexpected issues.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    description: Error code for the server issue.
                  error:
                    type: string
                    description: Error message indicating the server issue.
              examples:
                internal-error:
                  summary: Internal server error
                  value:
                    errorCode: "INTERNAL_ERROR"
                    error: "An unexpected error occurred. Please try again later."
  /api/v1/payouts:
    post:
      summary: Upload a new file for payouts
      operationId: uploadPayoutFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - requestId
                - file
              properties:
                requestId:
                  type: string
                  description: Unique identifier for the request.
                file:
                  type: string
                  format: binary
                  description: File to be uploaded.
      responses:
        '200':
          description: File uploaded successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    description: Request identifier.
                  message:
                    type: string
                    example: "File uploaded successfully."
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid file format."
    put:
      summary: Override an existing payout file
      operationId: overridePayoutFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - requestId
                - file
              properties:
                requestId:
                  type: string
                  description: Identifier of the file to be overridden.
                file:
                  type: string
                  format: binary
                  description: Replacement file to upload.
      responses:
        '200':
          description: File overridden successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    description: Identifier of the overridden file.
                  message:
                    type: string
                    example: "File overridden successfully."
        '404':
          description: File not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "File with given requestId not found."
    patch:
      summary: Update an existing payout file incrementally
      operationId: updatePayoutFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - requestId
                - file
              properties:
                requestId:
                  type: string
                  description: Identifier of the file to be updated.
                file:
                  type: string
                  format: binary
                  description: Incremental file to be uploaded.
      responses:
        '200':
          description: File updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    description: Identifier of the updated file.
                  message:
                    type: string
                    example: "File updated successfully."
        '404':
          description: File not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "File with given requestId not found."
  /api/v1/payouts/{requestId}/status:
    get:
      summary: Fetch the processing status of a request
      operationId: getPayoutStatus
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: string
          description: Identifier of the request to fetch the status for.
      responses:
        '200':
          description: Status fetched successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    description: Identifier of the request.
                  status:
                    type: string
                    description: Current status of the request.
                    example: "Payment Completed"
                  details:
                    type: object
                    description: Additional details about the request processing.
                    properties:
                      successfulRows:
                        type: integer
                        example: 95
                      failedRows:
                        type: integer
                        example: 5
                      errors:
                        type: array
                        items:
                          type: object
                          properties:
                            row:
                              type: integer
                              example: 3
                            error:
                              type: string
                              example: "Invalid vendor ID."
                      resultFileUrl:
                        type: string
                        example: "https://s3.amazonaws.com/bucket-name/path-to-file.csv"
        '404':
          description: Request ID not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Request ID not found."
