openapi: 3.0.3
info:
  title: Netsuite API Contracts
  description: APIs to upload and update vendor mapping files for ingestion and processing.
  version: 1.0.0
paths:
  /api/v1/payouts/:
    post:
      summary: Upload a new file for processing payouts for vendors already registered. Gives a request Id to track further statuses.  
      description: Allows uploading an initial file for ingestion and processing via multipart form-data.
      operationId: uploadFile
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileContent:
                  type: string
                  format: binary
                  description: The file to upload. This must be the binary content of the file.
                metadata:
                  type: string
                  format: json
                  description: Metadata associated with the file upload, in JSON format.
              required:
                - fileContent
      responses:
        '200':
          description: File uploaded successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: File uploaded successfully.
                  cycleId:
                    type: string
                    example: 01936260-910b-721a-81e6-4277af8adb9c
                  processingStatus:
                    type: string
                    enum: [pending, in-progress, completed, failed]
                    example: pending
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: File upload failed.
                  details:
                    type: string
                    example: "Missing column name 'Amount' "
                  errorCode:
                    type: string
                    example: UPLOAD_ERROR
  /api/v1/payouts/{cycleId}:
    put:
      summary: Update an existing file by uploading a diff.
      description: Updates an existing file associated with the given request ID by uploading incremental changes via multipart form-data.
      operationId: updateFile
      security:
        - ApiKeyAuth: []
      parameters:
        - name: cycleId
          in: path
          required: true
          schema:
            type: string
            example: "01936260-910b-721a-81e6-4277af8adb9c"
          description: The unique identifier of the file update request.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                diffFile:
                  type: string
                  format: binary
                  description: The diff file to upload. This must be the binary content of the file.
                metadata:
                  type: string
                  format: json
                  description: Metadata associated with the file update, in JSON format.
              required:
                - diffFile
      responses:
        '200':
          description: File updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: File updated successfully.
                  requestId:
                    type: string
                    example: 12345
                  processingStatus:
                    type: string
                    enum: [pending, in-progress, completed, failed]
                    example: pending
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: File update failed.
                  details:
                    type: string
                    example: "Missing column name 'Amount' "
                  errorCode:
                    type: string
                    example: UPDATE_ERROR
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    Schema:
      type: object
      properties:
        id:
          type: integer
          format: int64
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SoumikBhattacharyya/NetSuite/1.0.0